[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "orange"
version = "0.1.112"
description = ""
authors = [ "Anderson Rodrigues <eusouanderson@outlook.com>",]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
pyside6 = "^6.8.0.2"
watchdog = "^6.0.0"
pyinstaller = "^6.11.1"
black = "^24.10.0"
requests = "^2.32.3"
beautifulsoup4 = "^4.12.3"
requests-html = "^0.10.0"
websockets = "8.1"

[tool.poetry.dependencies.lxml]
extras = [ "html-clean",]
version = "^5.3.0"

[tool.poetry.group.dev.dependencies]
cython = "^3.0.11"
