[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "orange"
version = "0.1.20"
description = ""
authors = [ "Anderson Rodrigues <eusouanderson@outlook.com>",]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
pyside6 = "^6.8.0.2"
watchdog = "^6.0.0"
pyinstaller = "^6.11.1"
black = "^24.10.0"
